name: Deploy to CapRover

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and deploy to CapRover
      run: |
        docker build -t modoboa-installer .
        docker tag modoboa-installer:latest captain.your-domain.com/modoboa-installer:latest
        docker push captain.your-domain.com/modoboa-installer:latest
      env:
        CAPROVER_SERVER: ${{ secrets.CAPROVER_SERVER }}
        CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
        CAPROVER_APP: ${{ secrets.CAPROVER_APP }}
